### ISSUE TITLE
FileNotFoundException: /tmp

### ISSUE THREAD

**Issue by JulianSauer** [bmustiata/jenny#54]
(Under Windows 10) simply running `jenny` results in

    Caught: java.io.FileNotFoundException: \tmp\jenny_1b49aa6c-84cf-4afb-9aa0-568b140f9702.log (The system cannot find the path specified)
    java.io.FileNotFoundException: \tmp\jenny_1b49aa6c-84cf-4afb-9aa0-568b140f9702.log (The system cannot find the path specified)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at parent_log_items.run(parent_log_items.groovy:2)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at jenny$_run_closure1.doCall(jenny.groovy:44)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at jenny.run(jenny.groovy:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

I then tried changing the workFolder in `myproject/.jenny/config` to `myproject/tmp/` which didn't change anything yet. So I tried `jenny -w tmp/` instead.
Maybe I misunderstood the syntax (I also tried `jenny -w=tmp/` and `jenny -w`) but it always results in exception I got earlier:

    Caught: java.io.FileNotFoundException: \true\jenny_1b49aa6c-84cf-4afb-9aa0-568b140f9702.log (The system cannot find the path specified)
    java.io.FileNotFoundException: \true\jenny_1b49aa6c-84cf-4afb-9aa0-568b140f9702.log (The system cannot find the path specified)

So I actually created the folder `myproject/true/` and now calling `jenny -w` works however the logs are saved under `myproject/true/*.log` while everything else is created under `myproject/tmp/` as specified in the config file earlier. Is this a bug or just a missing error message because I misunderstood the -w flag?

**Comment by bmustiata** [comment]
Hi Julian, requirement 1 from the README is *NIX :). I think I have a VM somewhere with Windows for my Germanium things, I'll try it out there, since it doesn't seem like a big issue to address, but more of a minor bug. Note, that I don't plan to really support Windows, but if you're centering your builds around docker, you should be fine.

**Comment by JulianSauer** [comment]
Ah I overrlooked that, sorry. Seems to me like the path for logs is not processed correctly since specifing the working directory in general works.

**Comment by bmustiata** [comment]
You're right! Great find. I never really bothered to change the path :)
